### ISSUE TITLE
Issues with the WebKit engine on apple devices

### ISSUE THREAD

**Issue by banxhu** [rs1703/Kasen#2]
It gives this on all WebKit browsers.

![73A5A442-45B1-4848-954B-E99DCA237E42](https://user-images.githubusercontent.com/99345227/163314942-aa2a572b-ee59-44f2-84c5-0734781b851c.png)

**Comment by rs1703** [comment]
Has something to do with workbox trying to access to a member of an undefined object. I have upgraded the workbox package but don't know whether it will fix the issue, so can you test it again? Might need to clear the site cache. Let me know, thank you.

**Comment by banxhu** [comment]
Hey it works great now... Also thx for the work on the project so far...

the thing with allowing scans to use custom css is also nice..

**Comment by banxhu** [comment]
Wait no
actually it still does it.... and i think it just renders for the first call and then after that it does not wanna work...

**Comment by rs1703** [comment]
For now I'll just remove the service worker since the issue is within the workbox package. In exchange users will no longer be able to open the website without internet connection but that shouldn't be a problem for most users. I have no idea how service worker works so I'll come up with a dependency-free solution at a later date.

If you modify the head and any other _head to insert your own css/js then just make sure that you re-add them after replacing the templates with the newer ones.

**Comment by banxhu** [comment]
Aight

**Comment by banxhu** [comment]
Working now!!!

**Comment by banxhu** [comment]
Can close for now...
